// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // Migrations/seed via la connexion directe (DIRECT_URL, hors pooler
    // transactionnel Prisma Migrate qui a besoin de verrous de session) ;
    // fallback sur DATABASE_URL en dev.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
